### PR TITLE
Rulesheet plugin attempt

### PR DESCRIPTION
**Pull request by Andarist**

### CODE REVIEW

**Comment by thysultan** [comment]
As an aside, the following seems to log the expected result:

```js
case RULESET: return console.log(element.type, stringify(element, stringify))
case MEDIA: case SUPPORTS: ++context, console.log(element.type, stringify(element, stringify)), --context
```

**Comment by Andarist** [comment]
Any ideas what approach should be explored to handle this?

**Comment by thysultan** [comment]
The following works as a callback middleware:

```js
import {serialize, stringify, prefixer, compile} from 'stylis'

function rulesheet (callback) {
	return function (element, value) { if (value = stringify(element, prefixer)) callback(value) }
}

serialize(compile('...'), rulesheet(value => console.log(value)))
```

**Comment by Andarist** [comment]
Ok, so the idea is to actually replace `middleware` with `rulesheet` - so a `rulesheet` is not a plugin, but rather a "finalizer" (like a `middleware`). I have not thought of that. Going to close this as I've seen you have already included a proposed `rulesheet` in the `middleware` branch.

**Comment by thysultan** [comment]
Yes that was the idea, but i've changed it now, will push my changes later today. This one should be more streamlined.

**Pull request closed without merging**
