### PR TITLE
Update typescript declarations

### PR DESCRIPTION
**Pull request by felixmosh**
Prove that they works :]

screenshot at jul 18 08-09-54
screenshot at jul 18 08-11-05
screenshot at jul 18 08-11-35
screenshot at jul 18 08-11-55

### CODE REVIEW

**Comment by thysultan** [comment]
Thanks.

**Comment by felixmosh** [comment]
Can you release new patch version?

**Comment by thysultan** [comment]
Sure, pushed 3.2.5

**Comment by felixmosh** [comment]
Thanx!

**Pull request merged**
