### PR TITLE
Add test for & inside a string

### PR DESCRIPTION
**Pull request by Andarist**

### CODE REVIEW

**Comment by thysultan** [comment]
I don't see this as an issue. In what real world case will this example reveal itself?

**Comment by Andarist** [comment]
This is, of course, a little bit contrived - but not that unlikely that I would consider this to be a non-issue. Personally, I don't think I would ever run into this, but I can imagine this being a problem for somebody. I can imagine some server-generated localization phrases (or just keys) including `&` put in the data attribute and selectors also generated based on those.

**Comment by thysultan** [comment]
The '&' is an invalid character for a css selector, so that should be a non-issue.

**Comment by Andarist** [comment]
`&` is not used here as part of the selector per se, but only as a part of the attribute value and it seems that this is a legit thing:
https://jsfiddle.net/vacdywzh/

**Comment by thysultan** [comment]
A good real-world-ish test for this could be:

```css
[href="https://css-tricks.com?a=1&b=2"] {...}
```

**Comment by Andarist** [comment]
Ok, I've merged in the proposed test as you have fixed the issue.

**Pull request merged**
